### ISSUE TITLE
Coflicting types for alias NSFont

### ISSUE THREAD

**Issue by furueili** [kishikawakatsumi/SECoreTextView#47]
i update Xcode to 6.2 , and i build my project found this error.
anyone know what's going on?
thx

![2015-03-11 8 49 30](https://cloud.githubusercontent.com/assets/1407724/6588365/b6d0338a-c7cb-11e4-9699-c5725648f1d4.png)

**Comment by jxdwinter** [comment]
+1

**Comment by jxdwinter** [comment]
I met the same issue.Anyone any idea?

**Comment by IrenBest** [comment]
The same issue,who can solve the question.

**Comment by kishikawakatsumi** [comment]
Thank you for reporting. I'll consider to solve the issue.

**Comment by Discobanan** [comment]
Please do! We also have this issue.

**Comment by xfxj23** [comment]
+1

**Comment by radioboo** [comment]
+1

**Comment by yezehui2002** [comment]
+1

**Comment by kishikawakatsumi** [comment]
Fixed https://github.com/kishikawakatsumi/SECoreTextView/pull/49 and release v0.8.4 including this fix.
Could you please check it?

Thank you for your patience and cooperation.
